# Generated by Django 5.1.3 on 2025-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolistapp", "0002_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="task_images/"),
        ),
        migrations.AddField(
            model_name="task",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
